services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: upzmg_db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DEV_PASSWORD: ${MSSQL_DEV_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
      MSSQL_DEV_PASSWORD: ${MSSQL_DEV_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - upzmg_db:/var/opt/mssql
      - ./init-db.sql:/var/opt/mssql/init-db.sql
      - ./start-mssql.sh:/var/opt/mssql/start-mssql.sh
    entrypoint: /var/opt/mssql/start-mssql.sh
    command: /opt/mssql/bin/sqlservr

volumes:
  upzmg_db:
